language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower typescript node-sass
  - bower install
  - cd source
  - tsc
  - node-sass game.scss game.css
  - cd ..

script: npm run-script deploy

env:
  global:
    - GH_REF: github.com/justindujardin/angular2-rpg.git
    - secure: eVKg9GoHN6AbIm8VdtfD+dp0Kbu4oh1j0ejVgRPrhtDY6aUJIaBCcMWhpyT6YhqhX8NA0Acf5DBtuW/ZqB1+kyDk2T2Cp1tcTTo3/Qh6GNab4VTB5aFKJdSpVG5LRwXqsEtdk6qvYG89jYJjO0gfUGL7r9fvG+Dzpr9v39RgZWdC1U02fOfhjBlSOTAfEd3UQDdQ0e2jPdhfI8GqlyM8pnHTSTJlhNIwuywH0CNYKJcGJd5Z9WIDcUgT1KvAAybdBvCLVODyQpTo32ZLUG7pQIE7fqibFB8luP2bUFlmiVX1Q5xVQRLHjjA3CoFR6T/uhNmwPynj5DEPE1FEVaRGD1hDTpae95CEpdezb5bvv1kRTCFnDk+ne5I5BPUtD8QgRh1JEdyLRNjd7Sh8RXUbnGSsmif/OTbogSqP+sNLyfRcnFIFzvikCFVUaNUh9LZasHBmnsAXd+b1euEuPle9RAzy7b94UR14pj9MaJ+PVM4jl9cDg6ZV+YXDUkjGS7N9YZDUMTUXWnI/oALfvpO7YIJsSKRzPoVK6R7cX4zP5FDtsaqhsG4AsywmA+RIu6Wj3/IMmVpmDF/PUqAZf00BdgW6S+a/hOs2BDXrkS50whqbPnlf+yyq4JdYK/hTNw5gJoJEopepxyXYve1fkCEyv0yzuDNY7ww6sX0XVh0cceg=
